[profile.default]
#auto_detect_solc = true
#solc_version = "0.8.5"
src = "src"
out = "out"
libs = ["lib"]
unchecked_cheatcode_artifacts = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
